src/Entity/Arret.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArretRepository")
 */
class Arret
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Employe", inversedBy="arrets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $employe;

    /**
     * @ORM\Column(type="date")
     */
    private $DateIn;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $DateOut;

    /**
     * @ORM\Column(type="boolean")
     */
    private $VisiteReprise;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Motif", inversedBy="arrets")
     */
    private $motif;

    private $nbreJour;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $rcent;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $rcinquante;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $rzero;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $rcarence;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Prolongation", mappedBy="arret", cascade={"persist","remove"})
     */
    private $prolongations;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\IJSS", mappedBy="Arret")
     */
    private $iJSS;

    /**
     * @ORM\Column(type="integer")
     */
    private $clos;

    /**
     * @ORM\Column(type="integer")
     */
    private $PrelSource;

    /**
     * @ORM\Column(type="boolean")
     */
    private $prevoyance;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commentaire", mappedBy="arret")
     */
    private $commentaires;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Maintien", inversedBy="arrets")
     */
    private $maintien;

    public function __construct()
    {
        $this->prolongations = new ArrayCollection();
        $this->iJSS = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNbreJour(): ?int
    {   $res = 0;
        /*if($this->DateIn)
        {
            if($this->DateOut)
            {
                $res = ($this->DateIn->diff($this->DateOut))->format('%a')+1;
            }
            else
            {
                $new = new \Datetime();
                $res = ($this->DateIn->diff($new))->format('%a')+1; 
            }
        }*/


        foreach ($this->getProlongations() as $prolongation)
        {
            $res += ($prolongation->getDateIn()->diff($prolongation->getDateOut()))->format('%a')+1;
        }

        return $res;
    }

    public function getEmploye(): ?Employe
    {
        return $this->employe;
    }

    public function setEmploye(?Employe $employe): self
    {
        $this->employe = $employe;

        return $this;
    }

    public function getDateIn(): ?\DateTimeInterface
    {
        return $this->DateIn;
    }

    public function setDateIn(\DateTimeInterface $DateIn): self
    {
        $this->DateIn = $DateIn;

        return $this;
    }

    public function getDateOut(): ?\DateTimeInterface
    {
        return $this->DateOut;
    }

    public function setDateOut(?\DateTimeInterface $DateOut): self
    {
        $this->DateOut = $DateOut;

        return $this;
    }

    public function getVisiteReprise(): ?bool
    {
        return $this->VisiteReprise;
    }

    public function setVisiteReprise(bool $VisiteReprise): self
    {
        $this->VisiteReprise = $VisiteReprise;

        return $this;
    }

    public function getMotif(): ?Motif
    {
        return $this->motif;
    }

    public function setMotif(?Motif $motif): self
    {
        $this->motif = $motif;

        return $this;
    }

    public function getRcent(): ?int
    {
        return $this->rcent;
    }

    public function setRcent(?int $rcent): self
    {
        $this->rcent = $rcent;

        return $this;
    }

    public function getRcinquante(): ?int
    {
        return $this->rcinquante;
    }

    public function setRcinquante(?int $rcinquante): self
    {
        $this->rcinquante = $rcinquante;

        return $this;
    }

    public function getRzero(): ?int
    {
        return $this->rzero;
    }

    public function setRzero(?int $rzero): self
    {
        $this->rzero = $rzero;

        return $this;
    }

    public function getRcarence(): ?int
    {
        return $this->rcarence;
    }

    public function setRcarence(?int $rcarence): self
    {
        $this->rcarence = $rcarence;

        return $this;
    }

    /**
     * @return Collection|Prolongation[]
     */
    public function getProlongations(): Collection
    {
        return $this->prolongations;
    }

    public function addProlongation(Prolongation $prolongation): self
    {
        if (!$this->prolongations->contains($prolongation)) {
            $this->prolongations[] = $prolongation;
            $prolongation->setArret($this);
        }

        return $this;
    }

    public function removeProlongation(Prolongation $prolongation): self
    {
        if ($this->prolongations->contains($prolongation)) {
            $this->prolongations->removeElement($prolongation);
            // set the owning side to null (unless already changed)
            if ($prolongation->getArret() === $this) {
                $prolongation->setArret(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return (string) "Arret N°".$this->getId()." pour  ". $this->getEmploye()." du ".$this->getDateIn()->format("d/m/Y")." au ". $this->getDateOut()->format("d/m/Y");
    }

    /**
     * @return Collection|IJSS[]
     */
    public function getIJSS(): Collection
    {
        return $this->iJSS;
    }

    public function addIJS(IJSS $iJS): self
    {
        if (!$this->iJSS->contains($iJS)) {
            $this->iJSS[] = $iJS;
            $iJS->setArret($this);
        }

        return $this;
    }

    public function removeIJS(IJSS $iJS): self
    {
        if ($this->iJSS->contains($iJS)) {
            $this->iJSS->removeElement($iJS);
            // set the owning side to null (unless already changed)
            if ($iJS->getArret() === $this) {
                $iJS->setArret(null);
            }
        }

        return $this;
    }

    public function getClos(): ?int
    {
        return $this->clos;
    }

    public function setClos(int $clos): self
    {
        $this->clos = $clos;

        return $this;
    }

    public function getPrelSource(): ?int
    {
        return $this->PrelSource;
    }

    public function setPrelSource(int $PrelSource): self
    {
        $this->PrelSource = $PrelSource;

        return $this;
    }

    public function getPrevoyance(): ?bool
    {
        return $this->prevoyance;
    }

    public function setPrevoyance(bool $prevoyance): self
    {
        $this->prevoyance = $prevoyance;

        return $this;
    }

    public function getIJP() :?int
    {
        $nbjour = 0;
        if( $this->prevoyance == 1)
        {
            if($this->employe->getCoeff()->getCadre() == 1)
            {
                $nbjour = $this->getNbreJour() - 30;
            }
            else
            {
                $nbjour = $this->getNbreJour() - 90;
            }
        }
        return $nbjour;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setArret($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->contains($commentaire)) {
            $this->commentaires->removeElement($commentaire);
            // set the owning side to null (unless already changed)
            if ($commentaire->getArret() === $this) {
                $commentaire->setArret(null);
            }
        }

        return $this;
    }

    public function getMaintien(): ?Maintien
    {
        return $this->maintien;
    }

    public function setMaintien(?Maintien $maintien): self
    {
        $this->maintien = $maintien;

        return $this;
    }
}

src/Entity/Employe.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EmployeRepository")
 */
class Employe
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Matricule;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="date")
     */
    private $dateEntree;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Service", inversedBy="employes")
     */
    private $Service;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Arret", mappedBy="employe")
     */
    private $arrets;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Coefficient", inversedBy="employes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Coeff;
    public $anciennete;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $sexe;

    /**
     * @ORM\Column(type="date")
     */
    private $dateNaissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $poste;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $dateSortie;

    /**
     * @ORM\Column(type="date")
     */
    private $dateDebutAnc;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Maintien", mappedBy="Employe")
     */
    private $maintiens;

    public function __construct()
    {
        $this->arrets = new ArrayCollection();
        $this->maintiens = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMatricule(): ?string
    {
        return $this->Matricule;
    }

    public function setMatricule(string $Matricule): self
    {
        $this->Matricule = $Matricule;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getDateEntree(): ?\DateTimeInterface
    {
        return $this->dateEntree;
    }

    public function setDateEntree(\DateTimeInterface $dateEntree): self
    {
        $this->dateEntree = $dateEntree;

        return $this;
    }

    public function getService(): ?Service
    {
        return $this->Service;
    }

    public function setService(?Service $Service): self
    {
        $this->Service = $Service;

        return $this;
    }

    /**
     * @return Collection|Arret[]
     */
    public function getArrets(): Collection
    {
        return $this->arrets;
    }

    public function addArret(Arret $arret): self
    {
        if (!$this->arrets->contains($arret)) {
            $this->arrets[] = $arret;
            $arret->setEmploye($this);
        }

        return $this;
    }

    public function removeArret(Arret $arret): self
    {
        if ($this->arrets->contains($arret)) {
            $this->arrets->removeElement($arret);
            // set the owning side to null (unless already changed)
            if ($arret->getEmploye() === $this) {
                $arret->setEmploye(null);
            }
        }

        return $this;
    }

    public function getCoeff(): ?Coefficient
    {
        return $this->Coeff;
    }

    public function setCoeff(?Coefficient $Coeff): self
    {
        $this->Coeff = $Coeff;

        return $this;
    }

    public function __toString()
    {
        return (string) $this->getMatricule() . " - ".$this->getNom()." ".$this->getPrenom();
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->dateNaissance;
    }

    public function setDateNaissance(\DateTimeInterface $dateNaissance): self
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    public function getPoste(): ?string
    {
        return $this->poste;
    }

    public function setPoste(string $poste): self
    {
        $this->poste = $poste;

        return $this;
    }

    public function getDateSortie(): ?\DateTimeInterface
    {
        return $this->dateSortie;
    }

    public function setDateSortie(\DateTimeInterface $dateSortie = null): self
    {   
        $this->dateSortie = $dateSortie;
        return $this;
    }

    public function getDateDebutAnc(): ?\DateTimeInterface
    {
        return $this->dateDebutAnc;
    }

    public function setDateDebutAnc(\DateTimeInterface $dateDebutAnc): self
    {
        $this->dateDebutAnc = $dateDebutAnc;

        return $this;
    }

    /**
     * @return Collection|Maintien[]
     */
    public function getMaintiens(): Collection
    {
        return $this->maintiens;
    }

    public function addMaintien(Maintien $maintien): self
    {
        if (!$this->maintiens->contains($maintien)) {
            $this->maintiens[] = $maintien;
            $maintien->setEmploye($this);
        }

        return $this;
    }

    public function removeMaintien(Maintien $maintien): self
    {
        if ($this->maintiens->contains($maintien)) {
            $this->maintiens->removeElement($maintien);
            // set the owning side to null (unless already changed)
            if ($maintien->getEmploye() === $this) {
                $maintien->setEmploye(null);
            }
        }

        return $this;
    }
}

src/Entity/Motif.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MotifRepository")
 */
class Motif
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Arret", mappedBy="motif")
     */
    private $arrets;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Court;

    public function __construct()
    {
        $this->arrets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    /**
     * @return Collection|Arret[]
     */
    public function getArrets(): Collection
    {
        return $this->arrets;
    }

    public function addArret(Arret $arret): self
    {
        if (!$this->arrets->contains($arret)) {
            $this->arrets[] = $arret;
            $arret->setMotif($this);
        }

        return $this;
    }

    public function removeArret(Arret $arret): self
    {
        if ($this->arrets->contains($arret)) {
            $this->arrets->removeElement($arret);
            // set the owning side to null (unless already changed)
            if ($arret->getMotif() === $this) {
                $arret->setMotif(null);
            }
        }

        return $this;
    }

    public function getCourt(): ?string
    {
        return $this->Court;
    }

    public function setCourt(string $Court): self
    {
        $this->Court = $Court;

        return $this;
    }

    public function __toString()
    {
        return (string) $this->getNom();
    }
}

templates/gestion/ajoutArret.html.twig
{% extends 'base.html.twig' %}

{% block body %}
   
    <br />
    <div class="jumbotron">
        <h1>Création d'un arrêt</h1>
        <hr class="my-4">
        {{ form_start(form)}}
        <div class="row">
            <div class="col">
                {{form_row(form.DateIn, {'label': 'Date de début','attr' : {'placeholder': 'Date ...'}})}}
            </div>
            <div class="col">
                {{form_row(form.DateOut, {'label': 'Date de fin','attr' : {'placeholder': 'Date ...'}})}}
            </div>
        </div>
        {{form_row(form.employe, {'label': 'Employé'})}}
        {{form_row(form.motif, {'label': 'Type'})}}
        {{form_row(form.load)}}

    </div>

        {% if employe is defined %}
            <div class="jumbotron">
                <div class="col-12">
                        <h3>Repartition pour l'arrêt en cours</h3>
                        <table class="table table-bordered">
                            <thead class="thead-dark">
                                <tr>
                                    <th>100%</th>
                                    <th>50%</th>
                                    <th>Ø</th>
                                    <th>Carence</th>
                                    <th>Prel Source</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>{{ arret.rcent }}</td>
                                    <td>{{ arret.rcinquante }}</td>
                                    <td>{{ arret.rzero }}</td>
                                    <td>{{ arret.rcarence }}</td>
                                    <td>{{ arret.prelSource }}</td> 
                                </tr>
                            </tbody>
                        </table>
                        {% if maintien is defined %}
                        <h3>Maintien</h3>
                        <table class="table table-bordered">
                            <thead class="thead-dark">
                                <tr>
                                    <th></th>
                                    <th>100%</th>
                                    <th>50%</th>
                                    <th>Ø</th>
                                    <th>Carence</th>
                                    <th>Prel Source</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Avant</td>
                                    <td>{{ arret.maintien.nb100 }}</td>
                                    <td>{{ arret.maintien.nb50 }}</td>
                                    <td>{{ arret.rzero }}</td>
                                    <td>{{ arret.rcarence }}</td>
                                    <td>{{ arret.prelSource }}</td> 
                                </tr>
                                <tr>
                                    <td>Apres</td>
                                    <td>{{ arret.rcent }}</td>
                                    <td>{{ arret.rcinquante }}</td>
                                    <td>{{ arret.rzero }}</td>
                                    <td>{{ arret.rcarence }}</td>
                                    <td>{{ arret.prelSource }}</td> 
                                </tr>
                            </tbody>
                        </table>
                        {% endif %}
                </div>
                <div class="col-4">
                    <p> Anciennete = {{ employe.anciennete }} mois </p>
                    <p> Coeffiecient = {{ employe.coeff.nom }}</p>
                    <p> Nombre de jour = {{ arret.nbreJour }}</p>
                    {% if arret.prevoyance %}
                        <p> Dossier prévoyance = <b>Oui</b></p>
                    {% else %}
                        <p> Dossier prévoyance = Non</p>
                    {% endif %}
                </div>
                <div class='offset-10 col-2'>
                    {{form_row(form.save)}}
                    <button type="submit" class="btn btn-danger">Annuler</button>
                </div>
            </div>
        {% endif %}
        {{form_end(form)}}
{% endblock %}
{% block javascripts %}{% endblock %}

templates/gestion/ajoutProlongation.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="jumbotron">
        <h1>Ajouter une prolongation</h1>
        <hr class="my-4">
        {{ form_start(form)}}
        <div class="row">
            <div class="col-lg-8">
                {{form_row(form.arret)}}
            </div>
            <div class="col-lg-4">
                {{form_row(form.type)}}
            </div>
        </div>
        <hr class="my-4">
        <div class="row">
            <div class="col-lg-6">
                {{form_row(form.dateIn, {'label': 'Date de début','attr' : {'placeholder': 'Date ...'}})}}
            </div>
            <div class="col-lg-6">
                {{form_row(form.dateOut, {'label': 'Date de fin','attr' : {'placeholder': 'Date ...'}})}}
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-lg-10">
            </div>
            <div class="col-lg-2">
                {{form_row(form.load)}} 
            </div>
        </div>
    </div>

    {% if test == 'Ok' %}
        <div class="container">
            <div class="row">
                <h3>Détails Arret</h3>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <p>Date fin d'arret : {{arret.dateOut|date("d/m/Y")}}</p>                    
                    {% if arret.VisiteReprise == 0 %}
                        <p>Visite Reprise : Faux</p>
                    {% else %}
                        <p>Visite Reprise : Vrai</p>
                    {% endif %}
                    <table class="table table-condensed">
                        <tr>
                            <th>100%</th>
                            <th>50%</th>
                            <th>Ø</th>
                            <th>Carence</th>
                            <th>Prel Src</th>
                        </tr>
                        <tr>
                            <td>{{ arret.rcent }}</td>
                            <td>{{ arret.rcinquante }}</td>
                            <td>{{ arret.rzero }}</td>
                            <td>{{ arret.rcarence }}</td>
                            <td>{{ arret.prelSource}}</td>
                        </tr>
                    </table>
                </div>
                <div class="col-lg-6">
                    <p>Date fin d'arret : {{ArretProvisoire.dateOut|date("d/m/Y")}}</p>
                    {% if ArretProvisoire.VisiteReprise == 0 %}
                        <p>Visite Reprise : Faux</p>
                    {% else %}
                        <p>Visite Reprise : Vrai</p>
                    {% endif %}
                    <table class="table table-condensed">
                        <tr>
                            <th>100%</th>
                            <th>50%</th>
                            <th>Ø</th>
                            <th>Carence</th>
                            <th>Prel Src</th>
                        </tr>
                        <tr>
                            <td>{{ ArretProvisoire.rcent }}</td>
                            <td>{{ ArretProvisoire.rcinquante }}</td>
                            <td>{{ ArretProvisoire.rzero }}</td>
                            <td>{{ ArretProvisoire.rcarence }}</td>
                            <td>{{ ArretProvisoire.prelSource }}</td>
                        </tr>
                    </table>
                    {% if (arret.prevoyance == 0) and (ArretProvisoire.prevoyance == 1) %}
                        <p><b> Attention, un dossier de prévoyance est à prévoir</b></p>
                    {% endif %}
                </div>
            </div>
        </div>

        {{form_row(form.save)}}
    {% endif %}
    {{ form_end(form)}}
{% endblock %}
{% block javascripts %}{% endblock %}

templates/gestion/employes.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h1>Gestion des employés</h1>
    <br/>
    <div class="section">
        <a type="button" class="btn btn-primary" href="{{ path('ajout_employes')}}">Ajouter </a>
    </div>
    <br/>
    <div class="section">
        <table class="table table-hover">
            <tr>
                <th>Matricule</th>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Service</th>
                <th>Date entrée</th>
                <th>Coefficient</th>
                <th>Actions</th>
            </tr>
            {% for employe in employes %}
            <tr>
                <td> {{ employe.matricule }} </td>
                <td> {{ employe.nom }} </td>
                <td> {{ employe.prenom }} </td>
                <td> {{ employe.service.nom }} </td>
                <td> {{ employe.dateEntree|date("m/d/Y") }} </td>

                    {% if employe.coeff.cadre %}
                        <td style='color:red'>{{ employe.coeff.nom }}</td>
                    {% else %}
                        <td style='color:blue'>{{ employe.coeff.nom }}</td>
                    {% endif %}

                <td>
                    <div class="btn-group" role="group" aria-label="">
                        <button type="button" class="btn btn-link">Modifier</button>
                        <form action="" method="post" id="delete-form">
                            <button type="submit" class="btn btn-link">
                                Supprimer
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}

templates/gestion/tableauArret.html.twig
    <table class="table table-hover">
        <tr>
            <th>Employé</th>
            <!--<th>Ancienneté</th>-->
            <th>Nature</th>
            <th>DU</th>
            <th>AU</th>
            <th>Nbre jours</th>
            <th>VM reprise</th>
            <th>Clos</th>
            <th class="text-center">Actions</th>
        </tr>
        {% for arret in arrets %}
        <tr>
            <td> {{ arret.employe.nom ~ ' ' ~ arret.employe.prenom }} </td>
            <!--<td> {{ arret.anciennete }} </td>-->
            <td> {{ arret.motif.nom }} </td>
            <td> {{ arret.dateIn|date("d/m/Y") }} </td>
            <td>
                {% if arret.dateOut %}
                    {{ arret.dateout|date("d/m/Y") }}
                {% endif %}
            </td>
            <td> {{ arret.nbreJour }} </td>
            <td> 
                {% if arret.VisiteReprise %}
                    Vrai
                {% else %}
                    Faux
                {% endif %}
            </td>
            <td>
                {% if arret.Clos == 1 %}
                    Clos
                {% elseif arret.Clos == 2 %}
                    <p style='color:red'>Litige</p>
                {% else %}
                    Actif
                {% endif %}
            </td>
            <td>
                {% if arret.Clos %}
                <!--<button class="btn btn-outline-warning" href="{{ path('IJSS_add', {'arretId': arret.id}) }}" disabled>IJSS</button>-->
                {% else %}
                <a type="button" class="btn btn-outline-success" href="{{ path('prolongation_add', {'arretId': arret.id}) }}">Prolonger</a>
                <a type="button" class="btn btn-outline-warning" href="{{ path('IJSS_add', {'arretId': arret.id}) }}">IJSS</a>
                {% endif %}
                <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#arretInfoModal" data-arret="{{ arret.id }}">Détails</button>
                <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#arretComModal" data-arret="{{ arret.id }}">Comm</button>
            </td>
        </tr>
        {% endfor %}
    </table>

    {% if pager.haveToPaginate %}
    <div class="col-6 offset-3">
        <ul class="pagination">
            {# pages 1 2 3 ... #}
            {% if pager.getNbPages() <= 3 %}
                {% for givenPage in 1..pager.getNbPages() %}
                    {% set state = '' %}
                    {% if  pager.getCurrentPage()  == givenPage %}
                        {% set state = 'active' %}
                    {% endif %}
                    <li class="page-item {{ state }}"><a class="page-link" onclick="changerPageFiltre({{ givenPage }})"> {{ givenPage }}</a></li>
                {%  endfor %}
            {% elseif pager.getCurrentPage()<=4%}
                {% for givenPage in 1..pager.getCurrentPage()+2 %}
                    {% set state = '' %}
                    {% if  pager.getCurrentPage()  == givenPage %}
                        {% set state = 'active' %}
                    {% endif %}
                    <li class="page-item {{ state }}"><a class="page-link" onclick="changerPageFiltre({{ givenPage }})"> {{ givenPage }}</a></li>
                {%  endfor %}
                <li class="page-item disabled">...</li>
                <li class="page-item active"><a class="page-link" onclick="changerPageFiltre({{ pager.getNbPages()}})">{{pager.getNbPages()}}</a></li>
            {% elseif pager.getCurrentPage() >= pager.getNbPages()-2 %}
                <li class="page-item active"><a class="page-link" onclick="changerPageFiltre(1)">1</a></li>
                <li class="page-item disabled">...</li>
                {% for givenPage in pager.getCurrentPage()-2..pager.getNbPages() %}
                    {% set state = '' %}
                    {% if  pager.getCurrentPage()  == givenPage %}
                        {% set state = 'active' %}
                    {% endif %}
                    <li class="page-item {{ state }}"><a class="page-link" onclick="changerPageFiltre({{ givenPage }})"> {{ givenPage }}</a></li>
                {%  endfor %}
            {% else %}
                <li class="page-item active"><a class="page-link" onclick="changerPageFiltre(1)">1</a></li>
                <li class="page-item disabled">...</li>
                {% for givenPage in pager.getCurrentPage()-2..pager.getCurrentPage()+2 %}
                    {% set state = '' %}
                    {% if  pager.getCurrentPage()  == givenPage %}
                        {% set state = 'active' %}
                    {% endif %}
                    <li class="page-item {{ state }}"><a class="page-link" onclick="changerPageFiltre({{ givenPage }})"> {{ givenPage }}</a></li>
                {%  endfor %}
                <li class="page-item disabled">...</li>
                <li class="page-item active"><a class="page-link" onclick="changerPageFiltre({{ pager.getNbPages()}})">{{pager.getNbPages()}}</a></li>
            {% endif %}
        </ul>
        </div>
    {% endif %}

    {# pagerfanta(pager, 'twitter_bootstrap', { 'proximity': 5}) #}